version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    container_name: minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: changeme
    command: server --console-address ":9001" /data

  redis:
    image: "redis:alpine"
    restart: always
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    ports:
      - "6379:6379"

volumes:
  minio_storage:
