# Changes here will be overwritten by Copier
_commit: 0.5.0
_src_path: https://github.com/fastapi-mvc/copier-project.git
aiohttp: true
author: Kevin Hertwig
chart_name: crypto-service
container_image_name: crypto-service
copyright_date: '2023'
email: kevin.hertwig@gmail.com
fastapi_mvc_version: 0.27.0
github_actions: false
helm: false
license: MIT
nix: false
package_name: crypto_service
project_description: Crypto service for the C2D marketplace to handle merkle trees
    within fairswap
project_name: crypto-service
redis: false
repo_url: https://github.com/amrap030/c2d-marketplace
script_name: crypto-service
version: 0.1.0
